### ISSUE TITLE
KeyError when removing stop words in canopy_index

### ISSUE THREAD

**Issue by oreccb** [dedupeio/dedupe#1069]
When I was training a model which used a canopy index, I ran into this exception:

```
/Users/brian/workspace/advisor-site/py-services/property-matching/venv/bin/python /Users/brian/workspace/advisor-site/py-services/property-matching/src/train.py
Traceback (most recent call last):
  File "/Users/brian/workspace/advisor-site/py-services/property-matching/src/train.py", line 28, in <module>
    main()
  File "/Users/brian/workspace/advisor-site/py-services/property-matching/src/train.py", line 24, in main
    train_property_deduper(aa_properties_df)
  File "/Users/brian/workspace/advisor-site/py-services/property-matching/src/train.py", line 15, in train_property_deduper
    deduper.train_deduper_console(config.get_config(), aa_properties_parsed_data)
  File "/Users/brian/workspace/advisor-site/py-services/property-matching/src/deduper.py", line 10, in train_deduper_console
    trainer.train(deduper_data)
  File "/Users/brian/workspace/advisor-site/py-services/property-matching/src/deduper.py", line 31, in train
    self.deduper.prepare_training(data, tf, sample_size=self.config.training_sample_size)
  File "/Users/brian/workspace/advisor-site/py-services/property-matching/venv/lib/python3.8/site-packages/dedupe/api.py", line 1298, in prepare_training
    self._sample(data, sample_size, blocked_proportion)
  File "/Users/brian/workspace/advisor-site/py-services/property-matching/venv/lib/python3.8/site-packages/dedupe/api.py", line 1324, in _sample
    self.active_learner = self.ActiveLearner(self.data_model,
  File "/Users/brian/workspace/advisor-site/py-services/property-matching/venv/lib/python3.8/site-packages/dedupe/labeler.py", line 429, in __init__
    self.blocker = DedupeBlockLearner(data_model,
  File "/Users/brian/workspace/advisor-site/py-services/property-matching/venv/lib/python3.8/site-packages/dedupe/labeler.py", line 266, in __init__
    self._index_predicates(examples_to_index)
  File "/Users/brian/workspace/advisor-site/py-services/property-matching/venv/lib/python3.8/site-packages/dedupe/labeler.py", line 276, in _index_predicates
    blocker.index(unique_fields, field)
  File "/Users/brian/workspace/advisor-site/py-services/property-matching/venv/lib/python3.8/site-packages/dedupe/blocking.py", line 144, in index
    index.initSearch()
  File "/Users/brian/workspace/advisor-site/py-services/property-matching/venv/lib/python3.8/site-packages/dedupe/tfidf.py", line 29, in initSearch
    self._index.initSearch()
  File "/Users/brian/workspace/advisor-site/py-services/property-matching/venv/lib/python3.8/site-packages/dedupe/canopy_index.py", line 36, in initSearch
    term = self.lexicon._words[wid]
KeyError: 1

Process finished with exit code 1
```

This started happening after we fixed a previous [issue](https://github.com/dedupeio/dedupe/issues/1029) with this [commit](https://github.com/dedupeio/dedupe/commit/1d01808f574f190a22c9d524c826caf54fc29cc6).

I think this [line](https://github.com/dedupeio/dedupe/blob/main/dedupe/canopy_index.py#L43) should really be a `self.lexicon._words.pop(wid)` call so the entry isn't removed and leads to a key error later.

I am using python 3.8.10 on MacOS with dedupe-2.0.13. A caveat here is that I patched my current version with the changes for the prior issue mentioned above so I don't have a clean install of dedupe with the latest main branch so there is always a chance that I have a broken package because of my edits (i don't think that is the case though..hopefully).

**Comment by fgregg** [comment]
i don’t see how the code could possibly have that error. could you post what your canopy_index looks like

**Comment by oreccb** [comment]
I pulled in the latest canopy_index.py file. 

I agree with you though, I don't see how this can occur. Since I encountered this, I have tweaked my model and it uses different predicates so this issue isn't currently affecting me. I don't want to waste your time tracking down something that might be some mess I made locally. I'm going to close this for now and if I encounter it later with a fresh install or have new information, I'll reopen.

**Comment by hlra** [comment]
I am stuck with the exact same error. I am trying to get dedupe to run for the very first time today so it might be due to some other local issues which I am overseeing but since this bug was reported very recently I thought this might be relevant. Had the same error when trying to use pandas-dedupe instead.

 ```
 File "<ipython-input-19-e5e6c01d9041>", line 1, in <module>
    linker.prepare_training(data1, data2, sample_size=1000)
  File "\Python39\site-packages\dedupe\api.py", line 1413, in prepare_training
    self.active_learner = self.ActiveLearner(
  File "\Python39\site-packages\dedupe\labeler.py", line 489, in __init__
    self.blocker = RecordLinkBlockLearner(data_model, data_1, data_2, index_include)
  File "\Python39\site-packages\dedupe\labeler.py", line 310, in __init__
    self._index_predicates(examples_to_index)
  File "\Python39\site-packages\dedupe\labeler.py", line 322, in _index_predicates
    blocker.index(unique_fields, field)
  File "\Python39\site-packages\dedupe\blocking.py", line 155, in index
    index.initSearch()
  File "\Python39\site-packages\dedupe\tfidf.py", line 32, in initSearch
    self._index.initSearch()
  File "\Python39\site-packages\dedupe\canopy_index.py", line 39, in initSearch
    term = self.lexicon._words[wid]

KeyError: 29
```

**Comment by hlra** [comment]
When I am not passing a dict from a dataframe to `prepare_training` but use the code from the linking example and read the data as CSVs I get a similar error:

```
Traceback (most recent call last):
  File "\IPython\core\interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-58-db52bf953b2f>", line 1, in <module>
    linker.prepare_training(data_1, data_2, sample_size=1000)
  File "\Python39\site-packages\dedupe\api.py", line 1413, in prepare_training
    self.active_learner = self.ActiveLearner(
  File "\Python39\site-packages\dedupe\labeler.py", line 489, in __init__
    self.blocker = RecordLinkBlockLearner(data_model, data_1, data_2, index_include)
  File "\Python39\site-packages\dedupe\labeler.py", line 298, in __init__
    self.block_learner = training.RecordLinkBlockLearner(
  File "\Python39\site-packages\dedupe\training.py", line 210, in __init__
    self.blocker.index_all(data_2)
  File "\Python39\site-packages\dedupe\blocking.py", line 196, in index_all
    self.index(unique_fields, field)
  File "\Python39\site-packages\dedupe\blocking.py", line 155, in index
    index.initSearch()
  File "\Python39\site-packages\dedupe\tfidf.py", line 32, in initSearch
    self._index.initSearch()
  File "\Python39\site-packages\dedupe\canopy_index.py", line 43, in initSearch
    word = self.lexicon._words.pop(wid)
KeyError: 2
```

**Comment by fgregg** [comment]
@hlra thanks your report this is a slightly different error, but we can track it here!

**Comment by hlra** [comment]
I tracked it down a bit further. In my case the cause seem to be the strings. I could not work out what exactly, whether it's punctuation or encoding. I want to match a full name field that includes titles such as Prof. Dr. James Smith and many other titles which leads to the error even after removing punctuation and fixing encoding, removing non-ascii letters and so on. It works when only using the first and last name so it seems to be some string preprocessing that is required or otherwise leads to this error.

I also get the error when specifying the ShortString field type with one of my variables. It works with the String type though. So, my best guess is that the error is thrown because something in the strings cannot be handled. It would be very helpful for newbies such as me to make the error message more intuitive and pointing to this problem. Also I have not understood yet what exactly the problem is with the strings..

Hope this helps, thanks for your work!

**Comment by hlra** [comment]
Yes, the error is fixed with the latest commit. Thanks!
