### ISSUE TITLE
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\username\\AppData\\Local\\Temp\\tmpfb6idzyr\\blocks.db'

### ISSUE THREAD

**Issue by mbkupfer** [dedupeio/dedupe#1074]
Getting this error when I use the static deduper with saved settings file. Any idea why this could be happening?

**Comment by mbkupfer** [comment]
Should've read the WHOLE stack trace. I realized that the issue was related to a KeyError and I'm guessing the propagating error was tied to an access issue since something was blocking the underlying blocks.db file.

Here is my whole stack trace in case the team would like to enhance some error handling that catches the key error sooner: 

```
Traceback (most recent call last):
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\site-packages\dedupe\api.py", line 246, in pairs
    con.executemany(
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\site-packages\dedupe\blocking.py", line 109, in __call__
    block_keys = predicate(instance, target=target)
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\site-packages\dedupe\predicates.py", line 105, in __call__
    column: str = record[self.field]
KeyError: 'client_names'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\MAXIM~1.KUP\\AppData\\Local\\Temp\\tmpsj73bly5\\blocks.db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\tempfile.py", line 802, in onerror
    _os.unlink(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\MAXIM~1.KUP\\AppData\\Local\\Temp\\tmpsj73bly5\\blocks.db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 50, in <module>
    main(args.config)
  File "C:\Users\maxim.kupfer\Dedupe\deduper-tool\matcher.py", line 12, in main
    clustered_dupes = matcher.partition(data, threshold=0.5)
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\site-packages\dedupe\api.py", line 174, in partition
    pair_scores = self.score(pairs)
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\site-packages\dedupe\api.py", line 109, in score
    matches = core.scoreDuplicates(
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\site-packages\dedupe\core.py", line 124, in scoreDuplicates
    first, record_pairs = peek(record_pairs)
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\site-packages\dedupe\core.py", line 279, in peek
    first = next(seq)
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\site-packages\dedupe\api.py", line 277, in pairs
    con.close()
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\tempfile.py", line 827, in __exit__
    self.cleanup()
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\tempfile.py", line 831, in cleanup
    self._rmtree(self.name)
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\tempfile.py", line 813, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\tempfile.py", line 805, in onerror
    cls._rmtree(path)
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\tempfile.py", line 813, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\shutil.py", line 599, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\shutil.py", line 596, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\MAXIM~1.KUP\\AppData\\Local\\Temp\\tmpsj73bly5\\blocks.db'
```
