### ISSUE TITLE
Error when installing dedupe on an M1 Mac with macOS 12.5.1

### ISSUE THREAD

**Issue by leifericf** [dedupeio/dedupe#1093]
Installing `dedupe` via `pip` 22.2.2 in a Conda environment on an M1 Mac with macOS 12.5.1 results in the following error:

```
$ pip install dedupe
Collecting dedupe
  Using cached dedupe-2.0.17-cp310-cp310-macosx_11_0_arm64.whl (63 kB)
Collecting numpy>=1.13
  Using cached numpy-1.23.2-cp310-cp310-macosx_11_0_arm64.whl (13.3 MB)
Collecting haversine>=0.4.1
  Downloading haversine-2.7.0-py2.py3-none-any.whl (6.9 kB)
Collecting Levenshtein-search==1.4.5
  Using cached Levenshtein_search-1.4.5.tar.gz (7.8 kB)
  Preparing metadata (setup.py) ... done
Collecting typing-extensions
  Downloading typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Collecting doublemetaphone
  Downloading DoubleMetaphone-1.1-cp310-cp310-macosx_11_0_arm64.whl (21 kB)
Collecting dedupe-variable-datetime
  Using cached dedupe_variable_datetime-0.1.5-py3-none-any.whl (4.8 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.1.2-cp310-cp310-macosx_12_0_arm64.whl (7.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 18.7 MB/s eta 0:00:00
Collecting categorical-distance>=1.9
  Using cached categorical_distance-1.9-py3-none-any.whl (3.3 kB)
Collecting simplecosine>=1.2
  Using cached simplecosine-1.2-py2.py3-none-any.whl (3.2 kB)
Collecting BTrees>=4.1.4
  Using cached BTrees-4.10.0.tar.gz (195 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [145 lines of output]
      Collecting setuptools
        Using cached setuptools-65.3.0-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting persistent
        Using cached persistent-4.9.0.tar.gz (119 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting zope.interface
        Using cached zope.interface-5.4.0-cp310-cp310-macosx_11_0_arm64.whl
      Collecting cffi
        Using cached cffi-1.15.1-cp310-cp310-macosx_11_0_arm64.whl (174 kB)
      Collecting pycparser
        Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
      Building wheels for collected packages: persistent
        Building wheel for persistent (setup.py): started
        Building wheel for persistent (setup.py): finished with status 'error'
        error: subprocess-exited-with-error

        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [30 lines of output]
            /Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
              warnings.warn(
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/h2/43rsy7m12cs6mp6d5y141cnc0000gn/T/pip-install-gtsw2phg/persistent_147e55a8b1344138b8b2bf151d96852d/setup.py", line 88, in <module>
                setup(name='persistent',
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
                _install_setup_requires(attrs)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
                dist.fetch_build_eggs(dist.setup_requires)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
                resolved_dists = pkg_resources.working_set.resolve(
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
                dist = best[req.key] = env.best_match(
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
                return self.obtain(req, installer)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
                return installer(requirement)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
                return fetch_build_egg(self, req)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
                wheel.install_as_egg(dist_location)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/wheel.py", line 96, in install_as_egg
                self._install_as_egg(destination_eggdir, zf)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/wheel.py", line 104, in _install_as_egg
                self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/wheel.py", line 148, in _convert_metadata
                os.rename(dist_info, egg_info)
            OSError: [Errno 66] Directory not empty: '/private/var/folders/h2/43rsy7m12cs6mp6d5y141cnc0000gn/T/pip-install-gtsw2phg/persistent_147e55a8b1344138b8b2bf151d96852d/.eggs/cffi-1.15.1-py3.10-macosx-11.0-arm64.egg/cffi-1.15.1.dist-info' -> '/private/var/folders/h2/43rsy7m12cs6mp6d5y141cnc0000gn/T/pip-install-gtsw2phg/persistent_147e55a8b1344138b8b2bf151d96852d/.eggs/cffi-1.15.1-py3.10-macosx-11.0-arm64.egg/EGG-INFO'
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for persistent
        Running setup.py clean for persistent
        error: subprocess-exited-with-error

        × python setup.py clean did not run successfully.
        │ exit code: 1
        ╰─> [30 lines of output]
            /Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
              warnings.warn(
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/h2/43rsy7m12cs6mp6d5y141cnc0000gn/T/pip-install-gtsw2phg/persistent_147e55a8b1344138b8b2bf151d96852d/setup.py", line 88, in <module>
                setup(name='persistent',
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
                _install_setup_requires(attrs)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
                dist.fetch_build_eggs(dist.setup_requires)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
                resolved_dists = pkg_resources.working_set.resolve(
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
                dist = best[req.key] = env.best_match(
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
                return self.obtain(req, installer)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
                return installer(requirement)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
                return fetch_build_egg(self, req)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
                wheel.install_as_egg(dist_location)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/wheel.py", line 96, in install_as_egg
                self._install_as_egg(destination_eggdir, zf)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/wheel.py", line 104, in _install_as_egg
                self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/wheel.py", line 148, in _convert_metadata
                os.rename(dist_info, egg_info)
            OSError: [Errno 66] Directory not empty: '/private/var/folders/h2/43rsy7m12cs6mp6d5y141cnc0000gn/T/pip-install-gtsw2phg/persistent_147e55a8b1344138b8b2bf151d96852d/.eggs/cffi-1.15.1-py3.10-macosx-11.0-arm64.egg/cffi-1.15.1.dist-info' -> '/private/var/folders/h2/43rsy7m12cs6mp6d5y141cnc0000gn/T/pip-install-gtsw2phg/persistent_147e55a8b1344138b8b2bf151d96852d/.eggs/cffi-1.15.1-py3.10-macosx-11.0-arm64.egg/EGG-INFO'
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for persistent
      Failed to build persistent
      Installing collected packages: wheel, setuptools, pycparser, zope.interface, cffi, persistent
        Running setup.py install for persistent: started
        Running setup.py install for persistent: finished with status 'error'
        error: subprocess-exited-with-error

        × Running setup.py install for persistent did not run successfully.
        │ exit code: 1
        ╰─> [30 lines of output]
            /Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
              warnings.warn(
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/h2/43rsy7m12cs6mp6d5y141cnc0000gn/T/pip-install-gtsw2phg/persistent_147e55a8b1344138b8b2bf151d96852d/setup.py", line 88, in <module>
                setup(name='persistent',
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
                _install_setup_requires(attrs)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
                dist.fetch_build_eggs(dist.setup_requires)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
                resolved_dists = pkg_resources.working_set.resolve(
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
                dist = best[req.key] = env.best_match(
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
                return self.obtain(req, installer)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
                return installer(requirement)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
                return fetch_build_egg(self, req)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
                wheel.install_as_egg(dist_location)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/wheel.py", line 96, in install_as_egg
                self._install_as_egg(destination_eggdir, zf)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/wheel.py", line 104, in _install_as_egg
                self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
              File "/Users/username/opt/miniconda3/envs/project-name/lib/python3.10/site-packages/setuptools/wheel.py", line 148, in _convert_metadata
                os.rename(dist_info, egg_info)
            OSError: [Errno 66] Directory not empty: '/private/var/folders/h2/43rsy7m12cs6mp6d5y141cnc0000gn/T/pip-install-gtsw2phg/persistent_147e55a8b1344138b8b2bf151d96852d/.eggs/cffi-1.15.1-py3.10-macosx-11.0-arm64.egg/cffi-1.15.1.dist-info' -> '/private/var/folders/h2/43rsy7m12cs6mp6d5y141cnc0000gn/T/pip-install-gtsw2phg/persistent_147e55a8b1344138b8b2bf151d96852d/.eggs/cffi-1.15.1-py3.10-macosx-11.0-arm64.egg/EGG-INFO'
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure

      × Encountered error while trying to install package.
      ╰─> persistent

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Conda `environment.yml` file:

```
name: project-name
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - libffi=3.4.2
  - libsqlite=3.39.2
  - libzlib=1.2.12
  - ncurses=6.3
  - openssl=3.0.5
  - pip=22.2.2
  - python=3.10.5
  - python_abi=3.10
  - readline=8.1.2
  - setuptools=65.0.2
  - sqlite=3.39.2
  - tk=8.6.12
  - tzdata=2022c
  - wheel=0.37.1
  - xz=5.2.6
prefix: /Users/username/opt/miniconda3/envs/project-name
```

**Comment by leifericf** [comment]
The installation also went smoothly when I switched to Python 3.9.

**Comment by fgregg** [comment]
for some reason persistent does this sometimes.
