### ISSUE TITLE
Error in read/write Training

### ISSUE THREAD

**Issue by BenderV** [dedupeio/dedupe#569]
Having exactly the same setup as https://dedupeio.github.io/dedupe-examples/docs/pgsql_big_dedupe_example.html. I have the following bugs the second time I'm trying to label data (I just added an option to "train" a second time)

```python
if option_train is False and os.path.exists(settings_path)
   ...
else:  # train 
```` 

I'm using Python3.5 with osx.

```python
Traceback (most recent call last):
  File "/Users/SmileOS/anaconda3/envs/theano_python35/lib/python3.5/site-packages/dedupe/api.py", line 760, in _checkRecordPair
    record_pair[0].keys() and record_pair[1].keys()
AttributeError: 'list' object has no attribute 'keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dedup.py", line 105, in <module>
    dedup(train=args.train)
  File "dedup.py", line 57, in dedup
    deduper.readTraining(tf)
  File "/Users/SmileOS/anaconda3/envs/theano_python35/lib/python3.5/site-packages/dedupe/api.py", line 644, in readTraining
    self.markPairs(training_pairs)
  File "/Users/SmileOS/anaconda3/envs/theano_python35/lib/python3.5/site-packages/dedupe/api.py", line 719, in markPairs
    self._checkTrainingPairs(labeled_pairs)
  File "/Users/SmileOS/anaconda3/envs/theano_python35/lib/python3.5/site-packages/dedupe/api.py", line 739, in _checkTrainingPairs
    self._checkRecordPair(pair)
  File "/Users/SmileOS/anaconda3/envs/theano_python35/lib/python3.5/site-packages/dedupe/api.py", line 762, in _checkRecordPair
    raise ValueError("A pair of record_pairs must be made up of two "
ValueError: A pair of record_pairs must be made up of two dictionaries
```

My labeled.json looks like
```json
{"match": [
    {"__value__": [
        ["id_1", "valueA", "valueB"], 
        ["id_2", "valueA", "valueBis"]],
    "__class__": "tuple"}
],
"distinct": [
    {"__value__": [
        ["id_1", "valueC", "valueB"], 
        ["id_2", "valueD", "valueBis"]],
    "__class__": "tuple"}
]}
```

**Comment by fgregg** [comment]
If you could provide a minimal reproducible example, I can take a look at this.

**Comment by BenderV** [comment]
It's ok. I fixed it. The problem was that I was fetching data from Postgres, and so the format was a DictRow and not dictionary. Hence, it was saving data in list-like format `["id_1", "valueC", "valueB"]` instead of the usual dictionary.
