### ISSUE TITLE
float division

### ISSUE THREAD

**Issue by dlubom** [dedupeio/dedupe#639]
I get this error, this happens occasionally for some data:

INFO:dedupe.blocking:350000, 131.2893172 seconds
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Program Files\anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\dlubom\AppData\Roaming\Python\Python27\site-packages\dedupe\core.py", line 173, in mergeScores
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Program Files\anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\dlubom\AppData\Roaming\Python\Python27\site-packages\dedupe\core.py", line 113, in __call__
    filtered_pairs = self.fieldDistance(record_pairs)
  File "C:\Users\dlubom\AppData\Roaming\Python\Python27\site-packages\dedupe\core.py", line 137, in fieldDistance
    distances = self.data_model.distances(records)
  File "C:\Users\dlubom\AppData\Roaming\Python\Python27\site-packages\dedupe\datamodel.py", line 82, in distances
    record_2[field])
  File "affinegap\affinegap.pyx", line 115, in affinegap.affinegap.normalizedAffineGapDistance (affinegap/affinegap.c:1788)
  File "affinegap\affinegap.pyx", line 134, in affinegap.affinegap.normalizedAffineGapDistance (affinegap/affinegap.c:1615)
ZeroDivisionError: float division

**Comment by dlubom** [comment]
Ok, after debugging its look that I try to compare two empty string here:

distances[i,start:stop] = compare(record_1[field], record_2[field]) 

I should have here None of course.

But, maybe Dedupe should return/rice more information?

**Comment by herberthamaral** [comment]
Just leaving a comment in case anyone bumps into this and needs a quick fix: change `String` and `ShortString´ in your dedupe's variable definitions. I don't know the performance/accuracy impacts of this, but I don't expect much change.

**Comment by fgregg** [comment]
Missing data should be represented by `None` https://dedupe.readthedocs.io/en/latest/Variable-definition.html#missing-data

**Comment by sontata** [comment]
I have same proplem:

```
fields = [{'field': 'name', 'variable name': 'name',
               'type': 'String', 'has missing': True},

              {'field': 'address', 'type': 'String',
               'variable name': 'address', 'has missing': True},

              {'field': 'owner_be_guid', 'type': 'Exact',
               'variable name': 'owner_be_guid', 'has missing': True},

              {'type': 'Interaction',
               'interaction variables': ['name', 'address']}
              ]
Traceback (most recent call last):
  File "/home/sontata/PycharmProjects/test/test.py", line 52, in <module>
    deduper.sample(temp_d)
  File "/home/sontata/venv/lib/python3.6/site-packages/dedupe/api.py", line 794, in sample
    data, blocked_proportion, sample_size, original_length)
  File "/home/sontata/venv/lib/python3.6/site-packages/dedupe/labeler.py", line 307, in sample_combo
    self.classifier._init(self.candidates)
  File "/home/sontata/venv/lib/python3.6/site-packages/dedupe/labeler.py", line 157, in _init
    self.distances = self.transform(candidates)
  File "/home/sontata/venv/lib/python3.6/site-packages/dedupe/labeler.py", line 89, in transform
    return self.data_model.distances(pairs)
  File "/home/sontata/venv/lib/python3.6/site-packages/dedupe/datamodel.py", line 83, in distances
    record_2[field])
  File "affinegap/affinegap.pyx", line 115, in affinegap.affinegap.normalizedAffineGapDistance (affinegap/affinegap.c:1991)
  File "affinegap/affinegap.pyx", line 134, in affinegap.affinegap.normalizedAffineGapDistance (affinegap/affinegap.c:1824)
ZeroDivisionError: float division
```

**Comment by sontata** [comment]
How i get this error.
Rows: name, address, be_owner_guid. There are rows with empty name and not empty address, be_owner_guid. I trainning dedupe and do test run. Dedupe doesnt found duples, where name is empty. I add оne more  row, where empty name and not empty address and be_owner_guid, in learning  cluster.

**Comment by sontata** [comment]
If add row before first training, the error does not occur  the first time.

**Comment by fjsj** [comment]
Maybe `trainingDataDedupe` should handle this? It's common for the empty value to be empty string in cases of loading training data from a CSV.

**Comment by Sharmilinag** [comment]
I have faced an error ZeroDivisionError: division by zero while running dedupe to identify duplicate records. I have tried using "has missing" and replacing empty string with Null but still the error is same. Please advise me to resolve this.

**Comment by aaroneden** [comment]
@Sharmilinag Did you get a resolution to this?  I'm running into the same issue and haven't been able to figure it out :(
