### ISSUE TITLE
No more unlabeled examples to label

### ISSUE THREAD

**Issue by Nitin-Asthana** [dedupeio/dedupe#647]
Getting below error while using few training records and process abends when it reaches end of training set.
    dedupe.consoleLabel(deduper)
  File "C:\Python27\lib\site-packages\dedupe\convenience.py", line 42, in consoleLabel
    uncertain_pairs = deduper.uncertainPairs()
  File "C:\Python27\lib\site-packages\dedupe\api.py", line 703, in uncertainPairs
    return self.active_learner.pop()
  File "C:\Python27\lib\site-packages\dedupe\labeler.py", line 255, in pop
    raise IndexError("No more unlabeled examples to label")
IndexError: No more unlabeled examples to label

On trying to pass exception, getting other exceptions. When trying to write settings and training file, settings file is not getting loaded on next turn and program abends with error: SettingsFileLoadingException: Something has gone wrong with loading the settings file. Try deleting the file.

Has anyone encountered same issue? Would appreciate any help on this.

**Comment by MANTENN** [comment]
I still am receiving this error running python 3.8 and macOS Catalina 10.15.5 (19F101)

**Comment by MANTENN** [comment]
```
1/10 positive, 98/10 negative
Do these records refer to the same thing?
(y)es / (n)o / (u)nsure / (f)inished / (p)revious
n
Traceback (most recent call last):
  File "/usr/local/bin/csvdedupe", line 8, in <module>
    sys.exit(launch_new_instance())
  File "/usr/local/lib/python3.8/site-packages/csvdedupe/csvdedupe.py", line 180, in launch_new_instance
    d.main()
  File "/usr/local/lib/python3.8/site-packages/csvdedupe/csvdedupe.py", line 110, in main
    self.dedupe_training(deduper)
  File "/usr/local/lib/python3.8/site-packages/csvdedupe/csvhelpers.py", line 262, in dedupe_training
    dedupe.consoleLabel(deduper)
  File "/usr/local/lib/python3.8/site-packages/dedupe/convenience.py", line 36, in consoleLabel
    uncertain_pairs = deduper.uncertainPairs()
  File "/usr/local/lib/python3.8/site-packages/dedupe/api.py", line 714, in uncertainPairs
    return self.active_learner.pop()
  File "/usr/local/lib/python3.8/site-packages/dedupe/labeler.py", line 323, in pop
    raise IndexError("No more unlabeled examples to label")
IndexError: No more unlabeled examples to label
```

CLI Command

```
~/Desktop/10K\ recent.csv \
          --field_names firstName lastName address city state zipcode \
          --output_file output.csv \
          --sample_size 100
```

**Comment by aragornm-88** [comment]
Hi, any update on this issue? Still facing it on Python 3.7.8 and dedupe-2.0.8
