### ISSUE TITLE
BlockingError

### ISSUE THREAD

**Issue by thodrek** [dedupeio/dedupe#660]
Hi, I have been using dedupe to train a record matcher. The input records are stored in a python dictionary and such that multiple attributes may contain None values. Everything seems to be working fine during training via active learning. Then I store the output model as well as training examples for later use. At a later stage of my pipeline I load the trained model to identify matches over new input data that follow the exact same schema as the ones I used to train the model (in fact they are from a different split of the same dataset). The problem at this stage is that I get the following exception:

traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda/lib/python2.7/site-packages/dedupe/api.py", line 224, in match
    return list(clusters)
  File "/anaconda/lib/python2.7/site-packages/dedupe/api.py", line 121, in matchBlocks
    threshold=0)
  File "/anaconda/lib/python2.7/site-packages/dedupe/core.py", line 207, in scoreDuplicates
    raise BlockingError("No records have been blocked together. "
dedupe.core.BlockingError: No records have been blocked together. Is the data you are trying to match like the data you trained on?

Have you experienced a similar bug before? Any hints would be welcome.

**Comment by thodrek** [comment]
Any updates on this? One thing is that some of my entries have missing values. I have declared them as missing in the deduce schema but I still get the blocking error.

**Comment by fgregg** [comment]
there's not enough information here to know if this is a bug. If the data is pretty different (even if it has the same schema), then blocking rules may not put together the new data.

"No records have been blocked together. Is the data you are trying to match like the data you trained on?"

**Comment by thodrek** [comment]
Is there a way to deactivate blocking?

**Comment by fgregg** [comment]
You can make your own custom "blocks" that involved every combination of records and feed that to matchBlocks 

https://docs.dedupe.io/en/latest/API-documentation.html

**Comment by sahilocean** [comment]
dedupe.core.BlockingError: No records have been blocked together.

Traceback (most recent call last):
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/PycharmProjects/comercial_delivery_system/customer/viewsets.py", line 86, in create
    res = get_redunded_customer_data({'name': data.get('name', '')})
  File "/home/sahil/PycharmProjects/comercial_delivery_system/customer/remove_duplicate_rec.py", line 17, in get_redunded_customer_data
    cluster = deduper.match({1:data}, threshold)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/dedupe/api.py", line 225, in match
    return list(clusters)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/dedupe/api.py", line 122, in matchBlocks
    threshold=0)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/dedupe/core.py", line 215, in scoreDuplicates
    raise BlockingError("No records have been blocked together. "
dedupe.core.BlockingError: No records have been blocked together. Is the data you are trying to match like the data you trained on?

**Comment by amboulouma** [comment]
I have the similar issue without using the blocking.

I try to apply my model (setting file) to a different dataset with the same scheme, it is just another chunk of the data I have. I used the first chunk to train the model in order to use it to deduplicate the reste of my database.

Please help me.

**Comment by eadka** [comment]
Facing a similar issue when using the settings and training file on a new dataset. Tried deleting the settings file and retaining the training file. The algorithm gives a BlockingError in both cases. "BlockingError: No records have been blocked together. Is the data you are trying to match like the data you trained on?"

**Comment by SeregaKR** [comment]
I have the same error: 
> BlockingError: No records have been blocked together. Is the data you are trying to match like the data you trained on?
I selected 30 records from the database, created 10 doubles and used this for training. After this I tried using the program for the whole base including 30 doubles from the training. As a result I got the error.
Any help?

**Comment by reloaded001** [comment]
Same error.

Has anyone been able to fix this?

Cheers.

**Comment by SeregaKR** [comment]
It seems that we just have to use something else

**Comment by fgregg** [comment]
I closed the original bug report because [there wasn't enough information to diagnose](https://github.com/dedupeio/dedupe/issues/660#issuecomment-389545481). If you have this problem, please open a new issue.
