### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by az0** [dedupeio/dedupe#677]
````
Traceback (most recent call last):
  File "train_from_csv.py", line 45, in <module>
    linker.sample(data_1, data_2, 15000)
  File "c:\python36\lib\site-packages\dedupe\api.py", line 848, in sample
    original_length_2)
  File "c:\python36\lib\site-packages\dedupe\labeler.py", line 327, in sample_product
    sample_size)
  File "c:\python36\lib\site-packages\dedupe\labeler.py", line 72, in sample_product
    random_sample_size)
  File "c:\python36\lib\site-packages\dedupe\core.py", line 76, in randomPairsMatch
    dtype=int)
OverflowError: Python int too large to convert to C long
````

My issue seems like https://github.com/dedupeio/dedupe/issues/551 . That was in `randomPairs()` and mine is in `randomPairsMatch()`

I am on Windows 10 with Python 3.6.4 64-bit .

**Comment by az0** [comment]
I still see this error in randomPairsMatch(). Now I am using dedupe version 1.9.4 with Python 64-bit 3.7.0 on Windows 10.
