### ISSUE TITLE
Unexpected TypeError in deduper.sample()

### ISSUE THREAD

**Issue by amberjrivera** [dedupeio/dedupe#681]
macOS High Sierra 10.13.6
Python 3.6.5 :: Anaconda custom (64-bit)
dedupe Version: 1.9.2
Note: The CSV I'm reading in to create the data_d dictionary was created from a pandas dataframe (in which all dtypes are 'object', except rowID), using pandas.to_csv().
```
    variables = [
        {'field' : 'iK', 'type': 'String'},
        {'field' : 'pN', 'type': 'String', 'has missing' : True},
        {'field' : 'iA', 'type': 'Price', 'has missing' : True},
        {'field' : 'vN', 'type': 'Name'}, 
        {'field' : 'c9', 'type': 'Categorical',
             'categories' : ['NON', 'INT', 'NOTAX']},
        {'field' : 'description', 'type': 'Text'},
        {'field' : 'rev', 'type': 'Categorical',
             'categories' : ['0', '1']},
        {'field' : 'pS', 'type': 'Categorical',
             'categories' : ['CLEAR', 'ISSUED', 'VOID'], 'has missing' : True}
        ]

sample = round(df.shape[0] * .20)  #113116
deduper.sample(data_d, sample_size=sample) #data_d is of length 565578
```

Error:
Traceback (most recent call last):
  File "duplicates.py", line 142, in <module>
    deduper.sample(data_d, sample_size=sample)
  File "/Users/username/anaconda3/lib/python3.6/site-packages/dedupe/api.py", line 794, in sample
    data, blocked_proportion, sample_size, original_length)
  File "/Users/username/anaconda3/lib/python3.6/site-packages/dedupe/labeler.py", line 305, in sample_combo
    sample_size)
  File "/Users/username/anaconda3/lib/python3.6/site-packages/dedupe/labeler.py", line 44, in sample_combo
    data)
  File "/Users/username/anaconda3/lib/python3.6/site-packages/dedupe/sampling.py", line 26, in blockedSample
    *args))
  File "/Users/username/anaconda3/lib/python3.6/site-packages/dedupe/sampling.py", line 66, in dedupeSamplePredicates
    items)
  File "/Users/username/anaconda3/lib/python3.6/site-packages/dedupe/sampling.py", line 85, in dedupeSamplePredicate
    block_keys = predicate_function(column)
  File "/Users/username/anaconda3/lib/python3.6/site-packages/dedupe/predicates.py", line 483, in orderOfMagnitude
    if field > 0:
**TypeError: '>' not supported between instances of 'str' and 'int'**

**Comment by fgregg** [comment]
In your data, the filed `'iA'` should be numeric (ideally a float).

**Comment by amberjrivera** [comment]
Indeed. And, Price fields cannot include negative or zero values, as noted in the documentation.
