### ISSUE TITLE
Install error on macosx

### ISSUE THREAD

**Issue by crimsonalucard** [dedupeio/dedupe#688]
Under anaconda 3-5.2.0 and running this command:

`pip install Dedupe`

produces this: 

```
Collecting dedupe-hcluster (from dedupe)
  Using cached https://files.pythonhosted.org/packages/3d/df/8a7c25b272746b9726bcfd6fe9974aa5e4d7c39f63f4e055ee69c90cb220/dedupe-hcluster-0.3.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7s/wnqn6pr13tb2nbz5q7p54ncc0000gq/T/pip-install-oe9l01li/dedupe-hcluster/setup.py", line 19, in <module>
        include_dirs=[numpy.get_include()])])
      File "/Users/brianyeh/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 897, in cythonize
        aliases=aliases)
      File "/Users/brianyeh/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 777, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/Users/brianyeh/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 102, in nonempty
        raise ValueError(error_msg)
    ValueError: 'hcluster/_hierarchy.pyx' doesn't match any files
```

**Comment by reyah314** [comment]
Confirmed the same issue for me too, on Mac-OS High Sierra 10.13.4
latest version of Anaconda 3-5.2.0

```Collecting dedupe
  Using cached https://files.pythonhosted.org/packages/62/cf/7f6e03c4db8e6093ea790f9cdc2a7a644e2ec98821ff3d9ef924e12c544d/dedupe-1.9.2-cp36-cp36m-macosx_10_12_x86_64.whl
Requirement already satisfied: future>=0.14 in /Users/ri/anaconda3/lib/python3.6/site-packages (from dedupe) (0.16.0)
Collecting dedupe-variable-datetime (from dedupe)
  Using cached https://files.pythonhosted.org/packages/65/8f/d21f6acadcdfd681ee038153883b5673b8b76f790e465d791780e6b7bf60/dedupe_variable_datetime-0.1.5-py3-none-any.whl
Collecting doublemetaphone (from dedupe)
  Using cached https://files.pythonhosted.org/packages/4e/dc/649a2de49819dbf740a23721894cffd91a185ea1d479b7d76d67a01c3ef4/DoubleMetaphone-0.1-cp36-cp36m-macosx_10_11_x86_64.whl
Collecting highered>=0.2.0 (from dedupe)
  Using cached https://files.pythonhosted.org/packages/81/00/cbd902cfd14ad1992fcdaa11a615d47b36b6136dc690e19b0afa58c7365d/highered-0.2.1-py2.py3-none-any.whl
Collecting fastcluster (from dedupe)
  Using cached https://files.pythonhosted.org/packages/cf/6a/9e0028aed464bad3d8f3040a56a0252ddf3ea6aa66e21bae440452d7a37c/fastcluster-1.1.25-cp36-cp36m-macosx_10_12_x86_64.whl
Collecting Levenshtein-search (from dedupe)
  Using cached https://files.pythonhosted.org/packages/c3/d3/d699e66342ac4843032d732ac285f9f4722bd24760c78a4330c5cfb1b624/Levenshtein_search-1.4.4-cp36-cp36m-macosx_10_11_x86_64.whl
Collecting simplecosine>=1.2 (from dedupe)
  Using cached https://files.pythonhosted.org/packages/2d/22/6ea3a5ab8aea06d6563eb927e706f7342a00d1849c9be6143a2a7d84ddbd/simplecosine-1.2-py2.py3-none-any.whl
Collecting dedupe-hcluster (from dedupe)
  Using cached https://files.pythonhosted.org/packages/3d/df/8a7c25b272746b9726bcfd6fe9974aa5e4d7c39f63f4e055ee69c90cb220/dedupe-hcluster-0.3.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/n4/w612k4d56w92twslgkyg2rsr0000gn/T/pip-install-pm19wb8d/dedupe-hcluster/setup.py", line 19, in <module>
        include_dirs=[numpy.get_include()])])
      File "/Users/ri/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 897, in cythonize
        aliases=aliases)
      File "/Users/ri/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 777, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/Users/ri/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 102, in nonempty
        raise ValueError(error_msg)
    ValueError: 'hcluster/_hierarchy.pyx' doesn't match any files
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/n4/w612k4d56w92twslgkyg2rsr0000gn/T/pip-install-pm19wb8d/dedupe-hcluster/
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Errors regardless of conda env or virtualenv

**Comment by faxg** [comment]
+1 ... is there any workaround known?
Anaconda 4.5.10

**Comment by dorg-ekrolewicz** [comment]
I'm getting a similar error but relating to a different file:

`Collecting pyhacrf-datamade>=0.2.0 (from highered>=0.2.0->dedupe)
  Using cached https://files.pythonhosted.org/packages/56/eb/cc7b639af06e29844c3ff081bfe1fc11c7a46d27513e1270d8fe09d16deb/pyhacrf-datamade-0.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/v8/djbz3nbs619c9j9g5y8xk9yh0000gp/T/pip-install-52a1af1j/pyhacrf-datamade/setup.py", line 19, in <module>
        extra_compile_args = ["-ffast-math", "-O4"])])
      File "/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 920, in cythonize
        aliases=aliases)
      File "/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 800, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 125, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pyhacrf/algorithms.pyx' doesn't match any files`

**Comment by fgregg** [comment]
These should be resolved. Please reopen if you have further trouble.
