### ISSUE TITLE
dedupe.core.BlockingError: No records have been blocked together. Is the data you are trying to match like the data you trained on?

### ISSUE THREAD

**Issue by sahilocean** [dedupeio/dedupe#703]
Traceback (most recent call last):
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/PycharmProjects/comercial_delivery_system/customer/viewsets.py", line 86, in create
    res = get_redunded_customer_data({'name': data.get('name', '')})
  File "/home/sahil/PycharmProjects/comercial_delivery_system/customer/remove_duplicate_rec.py", line 17, in get_redunded_customer_data
    cluster = deduper.match({1:data}, threshold)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/dedupe/api.py", line 225, in match
    return list(clusters)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/dedupe/api.py", line 122, in matchBlocks
    threshold=0)
  File "/home/sahil/.virtualenvs/comercial_delivery_system/lib/python3.5/site-packages/dedupe/core.py", line 215, in scoreDuplicates
    raise BlockingError("No records have been blocked together. "
dedupe.core.BlockingError: No records have been blocked together. Is the data you are trying to match like the data you trained on?

**Comment by fgregg** [comment]
This can happen, if the data you are trying to match is not like the data you trained on.
