### ISSUE TITLE
Trouble using the method 'sample' for multiple examples

### ISSUE THREAD

**Issue by HarryShomer** [dedupeio/dedupe#705]
I'm running into some issues that kind of has me scratching my head.

The data I'm using is structured like:
```
data = {
    0: {'Artist': "ABBATE, Niccolò dell'", 'title': 'Chimney breast'', ......},
    1: {'Artist': 'ABEELE, Pieter van', 'title': Medal commemorating Charles II embarkation at Scheveningen', ......},
    2: {'Artist': 'AGOSTINO DI DUCCIO', 'title': Angels Playing a Lute and Tambourine', ......}.
    ....
    ....
    6683: {'Artist': 'Gyula Kosice', 'title': 'Reloj espacial', .......}
}
```

Here are my fields and the creation of the Dedupe object:
```
fields = [
        {'field': 'Artist', 'type': 'String'},
        {'field': 'title', 'type': 'String'}
    ]

deduper = dedupe.Dedupe(fields)
```

It fails when trying to take a sample
```
deduper.sample(df_dict)
 ```

Here's the (full) traceback I'm getting:
```
INFO:dedupe.canopy_index:Removing stop word OF
Traceback (most recent call last):
  File "/Users/Harry/spcm_3185/sculpture_classification/merge_datasets.py", line 66, in <module>
    main()
  File "/Users/Harry/spcm_3185/sculpture_classification/merge_datasets.py", line 42, in main
    deduper.sample(df_dict)
  File "/anaconda/lib/python3.6/site-packages/dedupe/api.py", line 794, in sample
    data, blocked_proportion, sample_size, original_length)
  File "/anaconda/lib/python3.6/site-packages/dedupe/labeler.py", line 313, in sample_combo
    index_data)
  File "/anaconda/lib/python3.6/site-packages/dedupe/labeler.py", line 233, in _init_combo
    self.block_learner = training.DedupeBlockLearner(preds, *args)
  File "/anaconda/lib/python3.6/site-packages/dedupe/training.py", line 89, in __init__
    blocker.indexAll(data)
  File "/anaconda/lib/python3.6/site-packages/dedupe/blocking.py", line 99, in indexAll
    self.index(unique_fields, field)
  File "/anaconda/lib/python3.6/site-packages/dedupe/blocking.py", line 70, in index
    index.initSearch()
  File "/anaconda/lib/python3.6/site-packages/dedupe/tfidf.py", line 29, in initSearch
    self._index.initSearch()
  File "/anaconda/lib/python3.6/site-packages/dedupe/canopy_index.py", line 29, in initSearch
    for wid, docs in self.index._wordinfo.items():
  File "/anaconda/lib/python3.6/site-packages/BTrees/_base.py", line 1218, in __iter__
    for k in getattr(bucket, itertype)(*iterargs):
  File "/anaconda/lib/python3.6/site-packages/BTrees/_base.py", line 397, in <genexpr>
    for i in xrange(*self._range(*args, **kw)))
IndexError: list index out of range
 ```

It's throwing an exception in the Btrees implementation you are using. 

I figured I was doing something wrong (and I probably still am) but I then cloned the [examples repository](https://github.com/dedupeio/dedupe-examples) and tried running the first example listed - ["CSV example - early childhood locations"](https://dedupeio.github.io/dedupe-examples/docs/csv_example.html). I got the same error:
```
$cd csv_example
$python csv_example.py
importing data ...
Traceback (most recent call last):
  File "csv_example.py", line 110, in <module>
    deduper.sample(data_d, 15000)
  File "/anaconda/lib/python3.6/site-packages/dedupe/api.py", line 794, in sample
    data, blocked_proportion, sample_size, original_length)
  File "/anaconda/lib/python3.6/site-packages/dedupe/labeler.py", line 313, in sample_combo
    index_data)
  File "/anaconda/lib/python3.6/site-packages/dedupe/labeler.py", line 233, in _init_combo
    self.block_learner = training.DedupeBlockLearner(preds, *args)
  File "/anaconda/lib/python3.6/site-packages/dedupe/training.py", line 89, in __init__
    blocker.indexAll(data)
  File "/anaconda/lib/python3.6/site-packages/dedupe/blocking.py", line 99, in indexAll
    self.index(unique_fields, field)
  File "/anaconda/lib/python3.6/site-packages/dedupe/blocking.py", line 70, in index
    index.initSearch()
  File "/anaconda/lib/python3.6/site-packages/dedupe/tfidf.py", line 29, in initSearch
    self._index.initSearch()
  File "/anaconda/lib/python3.6/site-packages/dedupe/canopy_index.py", line 29, in initSearch
    for wid, docs in self.index._wordinfo.items():
  File "/anaconda/lib/python3.6/site-packages/BTrees/_base.py", line 1218, in __iter__
    for k in getattr(bucket, itertype)(*iterargs):
  File "/anaconda/lib/python3.6/site-packages/BTrees/_base.py", line 397, in <genexpr>
    for i in xrange(*self._range(*args, **kw)))
IndexError: list index out of range
 ```

Fwiw, I'm running python 3.6.0 on MacOS High Sierra - 10.13.4. I also meet the requirement of at least "numpy>=1.9" (I have 1.14.5). I'd really appreciate any help.

**Comment by fgregg** [comment]
sample has been deprecated
