### ISSUE TITLE
NoneType object has not attribute 'settimeout'

### ISSUE THREAD

**Issue by carterrees** [dedupeio/dedupe#717]
I've run into this issue a couple of times. The data set isn't large, n = 194,000, and the code does run completely through on occassion. However, I can't figure out why this particular error comes up. Line 389 refers to "for cluster, scores in clustered_dupes:"

Traceback (most recent call last):
  File "customer_master_mysql.py", line 389, in <module>
    for cluster, scores in clustered_dupes:
  File "/home/carterrees/PycharmProjects/data_services_predictopotamus/venv_predictopotamus36/lib64/python3.6/site-packages/dedupe/api.py", line 115, in matchBlocks
    candidate_records = itertools.chain.from_iterable(self._blockedPairs(blocks))
  File "/home/carterrees/PycharmProjects/data_services_predictopotamus/venv_predictopotamus36/lib64/python3.6/site-packages/dedupe/api.py", line 254, in _blockedPairs
    block, blocks = core.peek(blocks)
  File "/home/carterrees/PycharmProjects/data_services_predictopotamus/venv_predictopotamus36/lib64/python3.6/site-packages/dedupe/core.py", line 383, in peek
    record = next(records)
  File "customer_master_mysql.py", line 341, in candidates_gen
    if row['block_id'] != block_id:
KeyError: 'block_id'
Exception ignored in: <bound method SSCursor.close of <pymysql.cursors.SSDictCursor object at 0x7fa24fc78a90>>
Traceback (most recent call last):
  File "/home/carterrees/PycharmProjects/data_services_predictopotamus/venv_predictopotamus36/lib64/python3.6/site-packages/pymysql/cursors.py", line 441, in close
  File "/home/carterrees/PycharmProjects/data_services_predictopotamus/venv_predictopotamus36/lib64/python3.6/site-packages/pymysql/connections.py", line 1168, in _finish_unbuffered_query
  File "/home/carterrees/PycharmProjects/data_services_predictopotamus/venv_predictopotamus36/lib64/python3.6/site-packages/pymysql/connections.py", line 656, in _read_packet
  File "/home/carterrees/PycharmProjects/data_services_predictopotamus/venv_predictopotamus36/lib64/python3.6/site-packages/pymysql/connections.py", line 687, in _read_bytes
AttributeError: 'NoneType' object has no attribute 'settimeout'
Exception ignored in: <bound method MySQLResult.__del__ of <pymysql.connections.MySQLResult object at 0x7fa24fc78da0>>
Traceback (most recent call last):
  File "/home/carterrees/PycharmProjects/data_services_predictopotamus/venv_predictopotamus36/lib64/python3.6/site-packages/pymysql/connections.py", line 1062, in __del__
  File "/home/carterrees/PycharmProjects/data_services_predictopotamus/venv_predictopotamus36/lib64/python3.6/site-packages/pymysql/connections.py", line 1168, in _finish_unbuffered_query
  File "/home/carterrees/PycharmProjects/data_services_predictopotamus/venv_predictopotamus36/lib64/python3.6/site-packages/pymysql/connections.py", line 656, in _read_packet
  File "/home/carterrees/PycharmProjects/data_services_predictopotamus/venv_predictopotamus36/lib64/python3.6/site-packages/pymysql/connections.py", line 687, in _read_bytes
AttributeError: 'NoneType' object has no attribute 'settimeout'

**Comment by carterrees** [comment]
This is fixed. Spacing was off in the py file which wasn't allowing objects to be create correctly. #spacingmatters
