### ISSUE TITLE
Set object has no attribute values

### ISSUE THREAD

**Issue by ChadMGeek** [dedupeio/dedupe#742]
I am an experienced programmer, but new to dedupe and to python in general, so this could be user error. I'm attempting to follow the MySQL example using my own data in MS SQL Server. My problem lies at the line: `deduper.sample(temp_d)`. I am getting the following error:

Traceback (most recent call last):
  File "GroupPersons.py", line 88, in <module>
    deduper.sample(temp_d)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\dedupe\api.py", line 787, in sample
    self._checkData(data)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\dedupe\api.py", line 798, in _checkData
    self.data_model.check(next(iter(viewvalues(data))))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\future\utils\__init__.py", line 298, in viewvalues
    func = obj.values
AttributeError: 'set' object has no attribute 'values'

**Comment by ChadMGeek** [comment]
One other thought that could be related. I was originally getting a syntax error at this line:
`temp_d = {i: for i,row in enumerate(c)}`

To resolve the error, I removed the colon:
`temp_d = {i for i,row in enumerate(c)}`

**Comment by ChadMGeek** [comment]
Changed `temp_d = {i: for i,row in enumerate(c)}` to `temp_d = dict((i, row) for i, row in enumerate(c))` and it fixed the issue. Found this solution in an example on another site.
