### ISSUE TITLE
"AttributeError: Attempting to block with an index predicate without indexing records" when 

### ISSUE THREAD

**Issue by ghing** [dedupeio/dedupe#762]
I'm getting this error when trying to link two tables using `csvlink`: `AttributeError: Attempting to block with an index predicate without indexing records`.

I do point csvlink to an existing training file in my configuration JSON and the traceback  shows calling `readTraining()`, so this might be a duplicate of #753.

Here's the traceback:

```
Traceback (most recent call last):
  File "/Users/ghing/.local/share/virtualenvs/my-venv--M_EXioh/lib/python3.6/site-packages/dedupe/predicates.py", line 201, in __call__
    centers = self.index.search(doc, self.threshold)
AttributeError: 'NoneType' object has no attribute 'search'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ghing/.local/share/virtualenvs/my-venv--M_EXioh/bin/csvlink", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/Users/ghing/.local/share/virtualenvs/my-venv--M_EXioh/lib/python3.6/site-packages/csvdedupe/csvlink.py", line 210, in launch_new_instance
    d.main()
  File "/Users/ghing/.local/share/virtualenvs/my-venv--M_EXioh/lib/python3.6/site-packages/csvdedupe/csvlink.py", line 137, in main
    self.dedupe_training(deduper)
  File "/Users/ghing/.local/share/virtualenvs/my-venv--M_EXioh/lib/python3.6/site-packages/csvdedupe/csvhelpers.py", line 257, in dedupe_training
    deduper.readTraining(tf)
  File "/Users/ghing/.local/share/virtualenvs/my-venv--M_EXioh/lib/python3.6/site-packages/dedupe/api.py", line 651, in readTraining
    self.markPairs(training_pairs)
  File "/Users/ghing/.local/share/virtualenvs/my-venv--M_EXioh/lib/python3.6/site-packages/dedupe/api.py", line 723, in markPairs
    self.active_learner.mark(examples, y)
  File "/Users/ghing/.local/share/virtualenvs/my-venv--M_EXioh/lib/python3.6/site-packages/dedupe/labeler.py", line 348, in mark
    learner.fit_transform(self.pairs, self.y)
  File "/Users/ghing/.local/share/virtualenvs/my-venv--M_EXioh/lib/python3.6/site-packages/dedupe/labeler.py", line 198, in fit_transform
    recall=1.0)
  File "/Users/ghing/.local/share/virtualenvs/my-venv--M_EXioh/lib/python3.6/site-packages/dedupe/training.py", line 31, in learn
    dupe_cover = Cover(self.blocker.predicates, matches)
  File "/Users/ghing/.local/share/virtualenvs/my-venv--M_EXioh/lib/python3.6/site-packages/dedupe/training.py", line 393, in __init__
    self._cover(predicates, pairs)
  File "/Users/ghing/.local/share/virtualenvs/my-venv--M_EXioh/lib/python3.6/site-packages/dedupe/training.py", line 401, in _cover
    in enumerate(pairs)
  File "/Users/ghing/.local/share/virtualenvs/my-venv--M_EXioh/lib/python3.6/site-packages/dedupe/training.py", line 402, in <setcomp>
    if (set(predicate(record_1)) &
  File "/Users/ghing/.local/share/virtualenvs/my-venv--M_EXioh/lib/python3.6/site-packages/dedupe/predicates.py", line 205, in __call__
    raise AttributeError("Attempting to block with an index "
AttributeError: Attempting to block with an index predicate without indexing records
```

**Comment by fgregg** [comment]
Looks like a dupe of #753, could you checkout https://github.com/dedupeio/dedupe/tree/populate_active_learner_with_training_data and see if that resolves it?

**Comment by ghing** [comment]
After reconfiguring the job to not use existing training data, I didn't encounter this error, so I do think this is a dupe of #753. I'm closing this and will try to test that branch if I have chance.
