### ISSUE TITLE
 Python int too large to convert to C ssize_t

### ISSUE THREAD

**Issue by kto-pond** [dedupeio/dedupe#780]
Running into the error:
OverflowError: Python int too large to convert to C ssize_t

Referenced [722](https://github.com/dedupeio/dedupe/pull/722/files) and [723](https://github.com/dedupeio/dedupe/pull/723) and made changes to core.py to int64 which then causes the error:

ValueError: dimensions are too large; arrays and shapes with a total size greater than 'intp' are not supported.

Calls:
Traceback (most recent call last):
  File "f:/XXXXXXXXXX/XXX/XXX/third_party_dedupe_test.py", line 105, in <module>
    deduper.sample(temp_d, temp_z)
  File "C:\Python\Python37-32\lib\site-packages\dedupe\api.py", line 933, in sample
    index_include=examples)
  File "C:\Python\Python37-32\lib\site-packages\dedupe\labeler.py", line 438, in __init__
    sample_size)
  File "C:\Python\Python37-32\lib\site-packages\dedupe\labeler.py", line 78, in sample
    random_sample_size)
  File "C:\Python\Python37-32\lib\site-packages\dedupe\core.py", line 77, in randomPairsMatch
    i, j = numpy.unravel_index(random_pairs, (n_records_A, n_records_B))
  File "<__array_function__ internals>", line 6, in unravel_index
ValueError: dimensions are too large; arrays and shapes with a total size greater than 'intp' are not supported.

**Comment by fgregg** [comment]
what are the values of n_records_A and n_records_B?
