### ISSUE TITLE
AttributeError on macOS, runs fine windows

### ISSUE THREAD

**Issue by ejmurra** [dedupeio/dedupe#781]
I'm using dedupe to deduplicate a small spreadsheet (680 rows). On my Windows machine dedupe runs correctly. When I try to run the same script on macOS 10.13.6 High Sierra, I get an AttributeError during the threshold step.

My script is nearly identical to this [example script](https://github.com/dedupeio/dedupe-examples/blob/master/csv_example/csv_example.py) except that I'm using a pandas dataframe massaged into dedupe data format with `df.to_dict("index")`.

Stack trace:
```
INFO:dedupe.api:((SimplePredicate: (firstTokenPredicate, p_addr), TfidfTextCanopyPredicate: (0.4, p_addr)),)
Traceback (most recent call last):
  File "/Users/emurray/PycharmProjects/foo/bar/dedupe_list.py", line 118, in <module>
    threshold = deduper.threshold(data_d, recall_weight=1)
  File "/Users/emurray/.virtualenvs/foo/lib/python3.6/site-packages/dedupe/api.py", line 245, in threshold
    return self.thresholdBlocks(blocked_pairs, recall_weight)
  File "/Users/emurray/.virtualenvs/foo/lib/python3.6/site-packages/dedupe/api.py", line 69, in thresholdBlocks
    candidate_records = itertools.chain.from_iterable(self._blockedPairs(blocks))
  File "/Users/emurray/.virtualenvs/foo/lib/python3.6/site-packages/dedupe/api.py", line 256, in _blockedPairs
    block, blocks = core.peek(blocks)
  File "/Users/emurray/.virtualenvs/foo/lib/python3.6/site-packages/dedupe/core.py", line 386, in peek
    record = next(records)
  File "/Users/emurray/.virtualenvs/foo/lib/python3.6/site-packages/dedupe/api.py", line 276, in _blockData
    for record_id, block in block_groups:
  File "/Users/emurray/.virtualenvs/foo/lib/python3.6/site-packages/dedupe/blocking.py", line 45, in __call__
    block_keys = predicate(instance, target=target)
  File "/Users/emurray/.virtualenvs/foo/lib/python3.6/site-packages/dedupe/predicates.py", line 298, in __call__
    for predicate in self]
  File "/Users/emurray/.virtualenvs/foo/lib/python3.6/site-packages/dedupe/predicates.py", line 298, in <listcomp>
    for predicate in self]
  File "/Users/emurray/.virtualenvs/foo/lib/python3.6/site-packages/dedupe/predicates.py", line 156, in __call__
    self.threshold)
  File "/Users/emurray/.virtualenvs/foo/lib/python3.6/site-packages/dedupe/tfidf.py", line 36, in search
    in self._index.apply(query_list, threshold)]
  File "/Users/emurray/.virtualenvs/foo/lib/python3.6/site-packages/dedupe/canopy_index.py", line 61, in apply
    results = results.byValue(qw * threshold)
AttributeError: 'IFBucket' object has no attribute 'byValue'
```

**Comment by fgregg** [comment]
can't reproduce.
