### ISSUE TITLE
KeyError: 'Field type String not valid. Valid types include Custom'

### ISSUE THREAD

**Issue by RahulBadenkal** [dedupeio/dedupe#790]
Hi, 
I was trying to build a windows exe that uses dedupe.
When I run the project normally in pycharm it works fine but when I make an exe out if it (using pyintstaller) I get the following error

> ERROR:root:Something unexpected happened while uploading data due to: ('Field type String not valid. Valid types include Custom',)
Traceback (most recent call last):
  File "lib\site-packages\dedupe\datamodel.py", line 156, in typifyFields
KeyError: 'String'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "engine\app\eel_funcs.py", line 275, in upload_data
  File "engine\app\execute.py", line 62, in set_up_model
  File "lib\site-packages\dedupe\api.py", line 189, in __init__
  File "lib\site-packages\dedupe\api.py", line 619, in __init__
  File "lib\site-packages\dedupe\datamodel.py", line 24, in __init__
  File "lib\site-packages\dedupe\datamodel.py", line 159, in typifyFields
KeyError: 'Field type String not valid. Valid types include Custom'

My fields are set to this:
fields = [
        {'field': 'Description', 'type': 'String'},
    ]
After writing some print statements before the line where error is happening I observed this:

> fields:  [{'field': 'Description', 'type': 'String'}]  # Code I wrote to debug
definition:  {'field': 'Description', 'type': 'String'}   # Code I wrote to debug
field_type:  String   # Code I wrote to debug
FIELD CLASSES:  {'Custom': <class 'dedupe.variables.base.CustomType'>}   # Code I wrote to debug
FIELD CLASSES KEYS:  dict_keys(['Custom'])   # Code I wrote to debug
ERROR:root:Something unexpected happened while uploading data due to: ('Field type String not valid. Valid types include Custom',)
Traceback (most recent call last):
  File "lib\site-packages\dedupe\datamodel.py", line 156, in typifyFields
KeyError: 'String'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "engine\app\eel_funcs.py", line 275, in upload_data
  File "engine\app\execute.py", line 62, in set_up_model
  File "lib\site-packages\dedupe\api.py", line 189, in __init__
  File "lib\site-packages\dedupe\api.py", line 619, in __init__
  File "lib\site-packages\dedupe\datamodel.py", line 24, in __init__
  File "lib\site-packages\dedupe\datamodel.py", line 159, in typifyFields
KeyError: 'Field type String not valid. Valid types include Custom'

It turns out that the FIELD_CLASS dict only consists of 'CUSTOM' class and missing all others ('String', ;ShortString', etc classes) so when I pass the field type 'String', It raises a KeyError.

**Comment by RahulBadenkal** [comment]
It turns out that in base.py file, all the imports are done dynamically so pyinstaller is unable able to pick up those imports, thus all the modules for all types (String, Date, Price, etc) are missing in the final exe.
I guess a pyinstaller-hook would have to created for dedupe to deal with this. So mostly an issue with pyinstaller, I will raise it there and close this one
