### ISSUE TITLE
Error in deduper.threshold

### ISSUE THREAD

**Issue by redsunbeer1** [dedupeio/dedupe#795]
Hi,

I am using Deduper to find duplicate records in my data.  The code runs correctly when it is run from Jupyter and even from the command prompt (using a main function).  

However I want to use a web page, that is built using Django, to run the Dedupe functions.  The same code that runs correctly from Jupyter and the command prompt throws the following error when it is called from a Django web page.

---------------------------------------------------------
Internal Server Error: /getmatchdata/
Traceback (most recent call last):
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xx\Documents\workspace\idm_dev\BaseIDM06Jan2020\idm\views\dataMatchView.py", line 150, in getmatchdata
    file = dedupe.processedOutput (filename, 'csvoutput2.csv', deduper)
  File "C:\Users\xx\Documents\workspace\idm_dev\BaseIDM06Jan2020\idm\functions\deduplicate.py", line 123, in processedOutput
    threshold = deduper.threshold(data_d, recall_weight=1)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dedupe\api.py", line 242, in threshold
    return self.thresholdBlocks(blocked_pairs, recall_weight)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dedupe\api.py", line 66, in thresholdBlocks
    candidate_records = itertools.chain.from_iterable(self._blockedPairs(blocks))
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dedupe\api.py", line 253, in _blockedPairs
    block, blocks = core.peek(blocks)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dedupe\core.py", line 370, in peek
    record = next(records)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dedupe\api.py", line 268, in _blockData
    self.blocker.indexAll(data_d)
AttributeError: 'NoneType' object has no attribute 'indexAll'

---------------------------------------------------------

Please provide a solution for the above error.

**Comment by redsunbeer1** [comment]
Finally found the reason for the issue.  It appears that the settings file used for dedupe was not be called from Django, because Django was looking for it in another directory (the base folder of the Django application).
