### ISSUE TITLE
dedupe 2.0.0 is not working with python3

### ISSUE THREAD

**Issue by rajeevmca1990** [dedupeio/dedupe#804]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/dedupe/__init__.py", line 6, in <module>
    from dedupe._init import *  # noqa
  File "/usr/local/lib/python3.5/dist-packages/dedupe/_init.py", line 1, in <module>
    from dedupe.api import StaticDedupe, Dedupe  # noqa: F401
  File "/usr/local/lib/python3.5/dist-packages/dedupe/api.py", line 71
    self._fingerprinter: Optional[blocking.Fingerprinter] = None

**Comment by vaneseltine** [comment]
It certainly works with Python 3. Perhaps a 3.5 issue?

**Comment by rajeevmca1990** [comment]
I have python3.5 installed it is not working with python3.5

**Comment by fgregg** [comment]
this is true. no plans to support python 3.5. supporting 3.6-3.8
