### ISSUE TITLE
Ran out of predicates & MemoryError during the method call 'deduper.partition(data_d, 0.5)'

### ISSUE THREAD

**Issue by Getuart-Istogu** [dedupeio/dedupe#805]
Hello everyone,

I got during my run a warning 'ran out of predicates' and during the cluster following error.
I orientated to the file 'csv_example.py' with the difference that I am using the method 'training_data_dedupe' instead of the active learning part. I am kindly confused that my only 5500 records with 6 fields caused such an increase in memory consumption.

Is there a way to reduce memory consumption. Maybe better-blocking predicates? If so, how is it possible to achieve that?

My predicates:
INFO:dedupe.training:Final predicate set:
INFO:dedupe.training:ExistsPredicate: (Exists, Site Name)
INFO:dedupe.training:ExistsPredicate: (Exists, Region)
INFO:dedupe.training:SimplePredicate: (sortedAcronym, Country)
INFO:dedupe.training:ExistsPredicate: (Exists, Postal Code)
INFO:dedupe.training:SimplePredicate: (commonFourGram, Country)

Traceback (most recent call last):
  File "dedupeAlgorithm.py", line 179, in <module>
    clustered_dupes = deduper.partition(data_d, 0.5)
  File "C:\Users\...\anaconda3\envs\dedupe_env\lib\site-packages\dedupe\api.py", line 173, in partition
    clusters = list(clusters)
  File "C:\Users\...\anaconda3\envs\dedupe_env\lib\site-packages\dedupe\api.py", line 188, in _add_singletons
    for record_ids, score in clusters:
  File "C:\Users\...\anaconda3\envs\dedupe_env\lib\site-packages\dedupe\api.py", line 303, in cluster
    yield from clustering.cluster(scores, threshold)
  File "C:\Users\...\anaconda3\envs\dedupe_env\lib\site-packages\dedupe\clustering.py", line 164, in cluster
    for sub_graph in dupe_sub_graphs:
  File "C:\Users\...\anaconda3\envs\dedupe_env\lib\site-packages\dedupe\clustering.py", line 37, in connected_components
    n_components = len(numpy.unique(sub_graph['pairs']))
  File "<__array_function__ internals>", line 6, in unique
  File "C:\Users\...\anaconda3\envs\dedupe_env\lib\site-packages\numpy\lib\arraysetops.py", line 263, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts)
  File "C:\Users\...\anaconda3\envs\dedupe_env\lib\site-packages\numpy\lib\arraysetops.py", line 303, in _unique1d
    ar = np.asanyarray(ar).flatten()
MemoryError: Unable to allocate 27.2 GiB for an array with shape (28488856,) and data type <U256

**Comment by Getuart-Istogu** [comment]
Okay did solve it myself. Was a mistake in the training data :D
