### ISSUE TITLE
 RuntimeWarning: overflow encountered in exp and FloatingPointError: NaN dissimilarity value.

### ISSUE THREAD

**Issue by deepesch** [dedupeio/dedupe#816]
I typically get this error when I increase the dataset size by a certain size. For smaller dataset it works file what could you be going wrong?

/opt/fingerprints/ml/lib64/python3.6/site-packages/rlr/lr.py:47: RuntimeWarning: overflow encountered in exp
  scores = np.exp(scores + self.bias) / (1 + np.exp(scores + self.bias))
/opt/fingerprints/ml/lib64/python3.6/site-packages/rlr/lr.py:47: RuntimeWarning: invalid value encountered in true_divide
  scores = np.exp(scores + self.bias) / (1 + np.exp(scores + self.bias))
/opt/fingerprints/ml/lib64/python3.6/site-packages/rlr/lr.py:47: RuntimeWarning: overflow encountered in exp
  scores = np.exp(scores + self.bias) / (1 + np.exp(scores + self.bias))
/opt/fingerprints/ml/lib64/python3.6/site-packages/rlr/lr.py:47: RuntimeWarning: invalid value encountered in true_divide
  scores = np.exp(scores + self.bias) / (1 + np.exp(scores + self.bias))
creating entity_map_primary2 database
Traceback (most recent call last):
  File "betaclustering.py", line 358, in <module>
    cluster_ids(clustered_dupes))
  File "/opt/fingerprints/ml/lib64/python3.6/site-packages/mysqlclient-1.3.12-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 281, in executemany
    self._get_db().encoding)
  File "/opt/fingerprints/ml/lib64/python3.6/site-packages/mysqlclient-1.3.12-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 305, in _do_execute_many
    for arg in args:
  File "betaclustering.py", line 37, in cluster_ids
    for cluster, scores in clustered_dupes:
  File "/opt/fingerprints/ml/lib64/python3.6/site-packages/dedupe/api.py", line 322, in cluster
    yield from clustering.cluster(scores, threshold)
  File "/opt/fingerprints/ml/lib64/python3.6/site-packages/dedupe/clustering.py", line 171, in cluster
    preserve_input=True)
  File "/opt/fingerprints/ml/lib64/python3.6/site-packages/fastcluster.py", line 247, in linkage
    linkage_wrap(N, X, Z, mthidx[method])
FloatingPointError: NaN dissimilarity value.

**Comment by fgregg** [comment]
this does not seem like a valid traceback? is this more than one error?

**Comment by deepesch** [comment]
These errors usually occurred together.

**Comment by fgregg** [comment]
please past a single traceback in a new issue.
