### ISSUE TITLE
AttributeError: Attempting to block with an index predicate without indexing records

### ISSUE THREAD

**Issue by az0** [dedupeio/dedupe#952]
I had a record linkage system working for a few years with dedupe 1.9 (thank you!). Now when trying to upgrade to dedupe 2.0.11, I get this during training

```
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\dedupe\predicates.py", line 217, in __call__
    centers = self.index.search(doc, self.threshold)
AttributeError: 'NoneType' object has no attribute 'search'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\train_from_csv.py", line 172, in <module>
    go()
  File "\train_from_csv.py", line 149, in go
    linker.mark_pairs(labeled_examples) # FIXME: this fails with "AttributeError: Attempting to block with an index predicate without indexing records"
  File "C:\Python37\lib\site-packages\dedupe\api.py", line 1185, in mark_pairs
    self.active_learner.mark(examples, y)
  File "C:\Python37\lib\site-packages\dedupe\labeler.py", line 376, in mark
    learner.fit_transform(self.pairs, self.y)
  File "C:\Python37\lib\site-packages\dedupe\labeler.py", line 213, in fit_transform
    recall=1.0)
  File "C:\Python37\lib\site-packages\dedupe\training.py", line 34, in learn
    match_cover = self.cover(matches)
  File "C:\Python37\lib\site-packages\dedupe\training.py", line 137, in cover
    in enumerate(pairs)
  File "C:\Python37\lib\site-packages\dedupe\training.py", line 138, in <genexpr>
    if (set(predicate(record_1)) &
  File "C:\Python37\lib\site-packages\dedupe\predicates.py", line 219, in __call__
    raise AttributeError("Attempting to block with an index "
````

All my (simplified) code, (fake) data sets, logs, and pip freeze are in this repository https://github.com/az0/dedupe-record-linkage-issue

**Comment by fgregg** [comment]
thanks for revealing an incomplete error message, and something that's not really documented.

if you are calling prepare_training, and then mark_pairs like this, the records in labeled_examples must be all be in the data_1 and data_2 values you pass to prepare_training.

it might be convenient for you to get your training data into the expected json file format, and then do prepare_training(data_1, data_2, training_data_file).

if you do that, dedupe will do the right thing for you without you having to alter data_1 and data_2.

hopefully, that will get you unstuck.

we'll update the docs and the error message.

**Comment by fgregg** [comment]
the thing to do here is to throw a custom noindex predicate and then catch that in the various methods and raise an relevant error

and update the docs on mark_pairs

**Comment by fgregg** [comment]
there's better error message and better docs in the new release, @az0 .

docs here: https://docs.dedupe.io/en/latest/API-documentation.html#dedupe.RecordLink.mark_pairs
