### ISSUE TITLE
TypeError: this type has no size

### ISSUE THREAD

**Issue by sbackmann** [dedupeio/dedupe#973]
Dear Dedupe team,

I'm trying to use the RecordLinkage of dedupe but the above Error keeps coming up. It doesn't matter whether I use my own data or the [record-linkage example](https://github.com/dedupeio/dedupe-examples/tree/master/record_linkage_example).
I'm using dedupe 2.0.13, macOS Monterey 12.1 and Python 3.6.8

      `Traceback (most recent call last):
        File "/Users/%%%/IdeaProjects/Record/RecordLinnk/record_linkage_example.py", line 166, in <module>
          linked_records = linker.join(data_1, data_2, 0.0)
        File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dedupe/api.py", line 502, in join
          pair_scores = self.score(pairs)
        File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dedupe/api.py", line 110, in score
          self.num_cores)
        File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dedupe/core.py", line 193, in scoreDuplicates
          offset = multiprocessing.Value('Q', 0, lock=RLock())
        File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/context.py", line 135, in Value
          ctx=self.get_context())
        File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/sharedctypes.py", line 73, in Value
          obj = RawValue(typecode_or_type, *args)
        File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/sharedctypes.py", line 48, in RawValue
          obj = _new_value(type_)
        File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/sharedctypes.py", line 39, in _new_value
          size = ctypes.sizeof(type_)
      TypeError: this type has no size`

I'm looking forward to any help.

**Comment by fgregg** [comment]
i think this is probably due to your python version. unfortunately, python 3.6 is end of life and we do not support it.

does the problem persist which a newer python version

**Comment by sbackmann** [comment]
> i think this is probably due to your python version. unfortunately, python 3.6 is end of life and we do not support it.
> 
> does the problem persist which a newer python version

Thanks, you're probably correct. As I have to use python 3.6, I tried an older dedupe version (2.0.3). This seems to work.
